(function(root, factory) {
  var palette = factory();
  root.TOURGRID_NATURAL_64_V1 = palette;
  if (typeof module === 'object' && module.exports) module.exports = palette;
})(typeof globalThis !== 'undefined' ? globalThis : this, function() {
  return Object.freeze({
    id: 'natural-64-v1',
    version: 1,
    colors: Object.freeze([
      { code: 'N01', hex: '#222222', name: 'Black' },
      { code: 'N02', hex: '#4E4A48', name: 'Charcoal' },
      { code: 'N03', hex: '#77736F', name: 'Mid Gray' },
      { code: 'N04', hex: '#B4B4B4', name: 'Soft Gray' },
      { code: 'N05', hex: '#D0CDC8', name: 'Light Gray' },
      { code: 'N06', hex: '#DDD2C9', name: 'Warm Gray' },
      { code: 'N07', hex: '#EAE6DE', name: 'Ivory Gray' },
      { code: 'N08', hex: '#FFFFFF', name: 'White' },
      { code: 'R01', hex: '#6B2530', name: 'Wine' },
      { code: 'R02', hex: '#9D0A00', name: 'Deep Red' },
      { code: 'R03', hex: '#A83C36', name: 'Brick Red' },
      { code: 'R04', hex: '#D42F37', name: 'Natural Red' },
      { code: 'R05', hex: '#D60A49', name: 'Magenta Red' },
      { code: 'R06', hex: '#E45E68', name: 'Coral Red' },
      { code: 'R07', hex: '#E5968D', name: 'Salmon' },
      { code: 'R08', hex: '#F2B8B0', name: 'Soft Red' },
      { code: 'S01', hex: '#7D4A43', name: 'Deep Skin' },
      { code: 'S02', hex: '#A96759', name: 'Warm Skin' },
      { code: 'S03', hex: '#C98572', name: 'Tan Skin' },
      { code: 'S04', hex: '#E3A08C', name: 'Peach Shadow' },
      { code: 'S05', hex: '#FF9874', name: 'Coral Peach' },
      { code: 'S06', hex: '#F3B9A5', name: 'Light Peach' },
      { code: 'S07', hex: '#F8D0C0', name: 'Pale Pink' },
      { code: 'S08', hex: '#FCEFE8', name: 'Blush White' },
      { code: 'O01', hex: '#8E4A24', name: 'Dark Ochre' },
      { code: 'O02', hex: '#D46322', name: 'Burnt Orange' },
      { code: 'O03', hex: '#D58C41', name: 'Earth Orange' },
      { code: 'O04', hex: '#F19900', name: 'Amber' },
      { code: 'O05', hex: '#F9C932', name: 'Golden Yellow' },
      { code: 'O06', hex: '#FBE598', name: 'Pale Yellow' },
      { code: 'O07', hex: '#F5EAB7', name: 'Cream Yellow' },
      { code: 'O08', hex: '#FBF5E7', name: 'Cream White' },
      { code: 'G01', hex: '#394B32', name: 'Deep Forest' },
      { code: 'G02', hex: '#526E43', name: 'Forest Green' },
      { code: 'G03', hex: '#6C6D00', name: 'Deep Olive' },
      { code: 'G04', hex: '#738F50', name: 'Muted Green' },
      { code: 'G05', hex: '#5F9E68', name: 'Natural Green' },
      { code: 'G06', hex: '#8DBB78', name: 'Light Green' },
      { code: 'G07', hex: '#B3B47B', name: 'Sage Olive' },
      { code: 'G08', hex: '#C0DA72', name: 'Yellow Green' },
      { code: 'C01', hex: '#244C51', name: 'Deep Teal' },
      { code: 'C02', hex: '#356E70', name: 'Muted Teal' },
      { code: 'C03', hex: '#4C9391', name: 'Natural Cyan' },
      { code: 'C04', hex: '#70B3AE', name: 'Soft Cyan' },
      { code: 'C05', hex: '#9BCFC3', name: 'Mint' },
      { code: 'C06', hex: '#3F7F95', name: 'Steel Cyan' },
      { code: 'C07', hex: '#6FAFC2', name: 'Lake Blue' },
      { code: 'C08', hex: '#B7DDE0', name: 'Pale Cyan' },
      { code: 'B01', hex: '#26334D', name: 'Blue Black' },
      { code: 'B02', hex: '#3F5F86', name: 'Muted Navy' },
      { code: 'B03', hex: '#668DB2', name: 'Natural Blue' },
      { code: 'B04', hex: '#A9C7DA', name: 'Pale Blue' },
      { code: 'V01', hex: '#4D3E5C', name: 'Deep Mauve' },
      { code: 'V02', hex: '#735A82', name: 'Muted Purple' },
      { code: 'V03', hex: '#9A7DA8', name: 'Soft Purple' },
      { code: 'V04', hex: '#C6AEC9', name: 'Pale Lavender' },
      { code: 'BR01', hex: '#3E2C27', name: 'Dark Brown' },
      { code: 'BR02', hex: '#60463A', name: 'Coffee' },
      { code: 'BR03', hex: '#805F4A', name: 'Natural Brown' },
      { code: 'BR04', hex: '#9B755C', name: 'Light Brown' },
      { code: 'BR05', hex: '#AA8F75', name: 'Gray Brown' },
      { code: 'BR06', hex: '#B09156', name: 'Golden Brown' },
      { code: 'BR07', hex: '#C8AD88', name: 'Sand' },
      { code: 'BR08', hex: '#E1CDAB', name: 'Beige' }
    ])
  });
});
